name: Go workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Literal syntax
        run: |
          echo "First line"
          echo "Second line"
      
      # Outputs: "first line echo second line"
      - name: Folded syntax
        run: >
          echo "First line"
          echo "Second line"

      - name: Run go application
        run: |
          cd ./app
          go version
          
          echo "now running the application from ci/cd pipeline"
          go run main.go
