name: Go workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Preparation
        run: |
          echo "First line"
          echo "Second line"
      
      - name: Folded
        run: >
          echo "First line"
          echo "Second line"
